RA-30
AndrewSolodovnikov/RecipeApp pull request #25
Opened 2024-10-23 10:06 UTC by AndrewSolodovnikov

2024-10-23 20:13 UTC, Churickoid requested changes
Не хватает анимации для кнопок навигации, нудно расширить navOptions в main activity с параметрами анимации.
navigate(R.id.categoriesListFragment, null, navOptions)
val navOptions = navOptions {
    anim {
        enter = R.anim.slide_in_right ...
    }
}

2024-10-23 20:13 UTC, Churickoid commented on app/src/main/java/com/sol/recipeapp/ui/category/CategoriesListFragment.kt
> +                    it.id
В RA-30 мы должны передавать полностью category, а не id. В nav_graph тебе надо пменять тип на Category и передавать еэ

2024-10-23 20:13 UTC, Churickoid commented on app/src/main/java/com/sol/recipeapp/ui/recipes/recipeslist/RecipesListFragment.kt
> +        categoryId = RecipesListFragmentArgs.fromBundle(requireArguments()).categoryId
В документации safe args описано как надо правильно извлекать данные из action.  Сейчас это делается не верно, к тому же мы ложны передавать всю категорию
![image](https://github.com/user-attachments/assets/25c8ce66-b343-4499-81c5-55cc695ca5b6)
https://developer.android.com/guide/navigation/use-graph/pass-data#Safe-args

2024-10-23 20:13 UTC, Churickoid commented on app/src/main/res/navigation/nav_graph.xml
> +            app:argType="integer" />
здесь надо ортедактироовать

2024-10-24 06:00 UTC, AndrewSolodovnikov commented
> Не хватает анимации для кнопок навигации, нудно расширить navOptions в main activity с параметрами анимации. navigate(R.id.categoriesListFragment, null, navOptions) val navOptions = navOptions { anim { enter = R.anim.slide_in_right ... } }

кайф, сделал собственные анимации простенькие на xml, спасибо

2024-10-24 06:03 UTC, AndrewSolodovnikov commented on app/src/main/java/com/sol/recipeapp/ui/category/CategoriesListFragment.kt
> +                    it.id
сделал полностью передачу объектов между фрагментами, в том числе и Recipe

какие преимущества при передачи объекта? почему не передавать каждый аргумент по отдельности?

2024-10-24 09:01 UTC, Churickoid approved these changes
Всё верно! Апрув. В тг отписал

2024-10-24 19:16 UTC, merged